// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearReader.png
var resourceKrankyBearReaderPngData []byte
var resourceKrankyBearReaderPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearReader.png",
	StaticContent: resourceKrankyBearReaderPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}
