[Details]
ID = "com.github.amarillier.KrankyBearReader"
Name = "KrankyBear Reader"
Creator = "Allan Marillier"
Version = "0.1.0"
Build = 2
Icon = "KrankyBearReader.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"